    <script src="<?php echo base_url('assets/user_parts/vendor/jquery/jquery.min.js')?>"></script>
    <script src="<?php echo base_url('assets/user_parts/vendor/popper.js')?>/umd/popper.min.js')?>"> </script>
    <script src="<?php echo base_url('assets/user_parts/vendor/bootstrap/js/bootstrap.min.js')?>"></script>
    <script src="<?php echo base_url('assets/user_parts/vendor/jquery.cookie/jquery.cookie.js')?>"> </script>
    <script src="<?php echo base_url('assets/user_parts/vendor/waypoints/lib/jquery.waypoints.min.js')?>"> </script>
    <script src="<?php echo base_url('assets/user_parts/vendor/jquery.counterup/jquery.counterup.min.js')?>"> </script>
    <script src="<?php echo base_url('assets/user_parts/vendor/owl.carousel/owl.carousel.min.js')?>"></script>
    <script src="<?php echo base_url('assets/user_parts/vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js')?>"></script>
    <script src="<?php echo base_url('assets/user_parts/js/jquery.parallax-1.1.3.js')?>"></script>
    <script src="<?php echo base_url('assets/user_parts/vendor/bootstrap-select/js/bootstrap-select.min.js')?>"></script>
    <script src="<?php echo base_url('assets/user_parts/vendor/jquery.scrollto/jquery.scrollTo.min.js')?>"></script>
    <script src="<?php echo base_url('assets/user_parts/js/front.js')?>"></script>